addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.10.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"           % "1.5.10")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.4.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.20")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"             % "0.9.34")
