addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.5.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"           % "1.5.6")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.17")
